use_frameworks!

platform :ios, '9.0'

target 'GLNetworking_Example' do
  pod 'GLNetworking', :path => '../'
#pod 'GLNetworking'

  target 'GLNetworking_Tests' do
    inherit! :search_paths
  end
end
